name: Test
on:
  - push
jobs:
  test-postgres:
    strategy:
      matrix:
        version: [10, 11, 12, 13, 14]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:${{ matrix.version }}
        env:
          POSTGRES_DB: db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          url: jdbc:postgresql://postgres:5432/db
          user: user
          password: password
          locations: filesystem:.github/workflows/sql
      - run: echo 'testing'
  test-mysql:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: bitnami/mysql:8.0
        env:
          MYSQL_DATABASE: db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          url: jdbc:mysql://mysql:3306/db
          user: user
          password: password
          locations: filesystem:.github/workflows/sql
      - run: echo 'testing'
